services:
  web:
    image: nginx
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./setup/docker/nginx/nginx_template.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'

  php:
    build:
      context: ./setup/docker
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/html

  node:
    build:
      context: ./setup/docker
      dockerfile: node.Dockerfile
    volumes:
      - ./:/assets
    ports:
      - '5173:5173'
    command: sh -c "npm install && npm run dev"

  db:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - mysqldata:/var/lib/mysql

  redis:
    image: redis:6
    volumes:
      - redisdata:/data

volumes:
  mysqldata:
  redisdata:
